### ISSUE TITLE
Marker height drifts

### ISSUE THREAD

**Issue by sevenbitbyte** [UbiquityRobotics/fiducials#73] opened 2017-05-11 16:34 UTC
The tf pose of the detected fiducials if very spatially correct however the visualization markers of the same fiducials has high vertical error.

![height-drift](https://cloud.githubusercontent.com/assets/662932/25960768/d7696cb6-362c-11e7-9a6e-042bf24a6cd1.png)

**Comment by jim-v** [comment] 2017-07-22 20:42
The tf shows the currently estimated pose of the fiducual relative to the camera, while the green and red cuboids show the position of the fiducials within the map.  By design, the map requires multiple pose estimates to update.  However, there have been some bug fixes, eg #83 since the issue was opened..  Can you please retry this, and save a bag file of /raspicam_node/image/compressed

**Comment by rohbotics** [comment] 2017-12-16 04:16
Closing due to staleness

**Closed as completed by rohbotics** 2017-12-16 04:16 UTC
