### ISSUE TITLE
Get bag file of fiducials

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/fiducials#86] opened 2017-07-01 20:35 UTC

**Comment by rohbotics** [comment] 2017-07-22 20:11
@jim-v needs to write some documentation for how to grab such a bagfile

**Comment by rohbotics** [comment] 2017-07-22 20:14
https://github.com/UbiquityRobotics/ubiquity_main/issues/57

**Comment by rohbotics** [comment] 2017-07-22 21:11
duplicate of #81

**Closed as completed by rohbotics** 2017-07-22 21:11 UTC
